// <auto-generated />
using Estalkei.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Estalkei.Data.Migrations
{
    [DbContext(typeof(EstalkeiContext))]
    [Migration("20191117190718_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Estalkei.Domain.Entities.ExchangeType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ExchangeType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Compra"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Venda"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
